// src/utils/specialFares.js
export const specialFares = {
  "Purok New Leganes": 17,
  "Bagacay": 17,
  "Provincial Jail": 17,
  "Bagong Sikat": 17,
  "Marville Homes": 17,
  "Agreda Subdivision Phase 1": 17,
  "Marbel School of Science and Technology": 17,
  "Agan Homes": 19,
  "Roamsceville Subdivision": 19,
  "Agan East": 19,
  "San Antonio Phase 1": 19,
  "San Antonio Phase 2": 19,
  "Agreda Phase 2": 19,
  "Hernandez Farm": 19,
  "City Mall": 15,
  "BDO": 15,
  "Triniville Subdivision": 17,
  "Purok Reyes Highway": 17,
  "Crossing Sueno Village ": 17,
  "Paraiso Verde": 17,
  "Cinco niñas": 17,
  "Sueno Subdivision": 19,
  "Guanzon Subdivision": 19,
  "Purok Reyes": 19,
  "Barangay Morales Proper": 19,
  "EMR Center": 19,
  "Kings College Campus": 21,
  "Viajera": 21,
  "SOCOTECO-1": 23,
  "KorBel": 23,
  "DXKI": 23,
  "Regency College": 23,
  "Southwind Subdivision": 23,
  "Agan North": 25,
  "Lauban Subdivision": 25,
  "Iglesia ni Cristo": 15,
  "YBL": 15,
  "Brigada FM": 15,
  "DXKR": 17,
  "Green Valler": 17,
  "IBED": 17,
  "Hall of Justice": 17,
  "Depita Subdivision": 17,
  "Gaisano": 19,
  "Crossing Diaz": 19,
  "Integrated Public Terminal": 19,
  "Crossing Dos": 19,
  "Purok Malipayon": 19,
  "New City Hall": 23,
  "Santos Subdivision": 23,
  "Villegas Subdivision": 23,
  "Purok Silangan": 23,
  "Allah Valley Hospital": 23,
  "Bombo Radyo": 25,
  "BIR": 25,
  "NIA": 25,
  "Purok Tony Ko": 25,
  "Crossing Guadalupe": 25,
  "Crossing Megaland": 25,
  "Crossing Cammella": 25,
  "Crossing Sais": 25,
  "Megaland Subdivision": 27,
  "The Farm": 29,
  "Regional Center": 31,
  "Purok Tuburan": 17,
  "Purok Nursery": 17,
  "Purok Hillside Barangay Sta. Cruz": 17,
  "Purok Siodina": 19,
  "Purok Tambling": 19,
};
